### PR TITLE
Kubernetes service accounts support

### PR DESCRIPTION
**Pull request by sercand**
Localkube does not create service accounts at the beginning which causes problems when using kubernetes api with InClusterConfig. This pull request creates a PEM certificate at start and uses it as service account certificate.

### CODE REVIEW

**Comment by ethernetdan** [comment]
Hey @sercand - thanks for the PR!

@mfburnett and I are working on a process around external contributions with the goal of all changes going through the same standards (with exceptions for hotfixes and non-code changes). Hopefully this will get up within the next week.

**Comment by luxas** [comment]
We need this for core Kubernetes localkube

**Comment by sercand** [comment]
@ethernetdan any update on this

**Comment by ethernetdan** [comment]
@sercand could you rebase and group the standard library imports? Otherwise LGTM

In order to ensure the chain of title for the contribution back to Kubernetes core, I'll need you to sign Redspread CLA. Is your github email the best place to reach you?

**Comment by sercand** [comment]
GitHub email is ok.


*Sercan Değirmenci*


2016-04-28 13:37 GMT+03:00 Dan Gillespie <notifications@github.com>:

**Comment by ethernetdan** [comment]
Just sent

**Comment by luxas** [comment]
Should we retarget this one for `minikube` now?

**Comment by ethernetdan** [comment]
@luxas I think that's a good idea

**Pull request closed without merging**
